In [1]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

In [2]:
df = df.rename(columns={
    "fname": "FirstName",
    "lname": "LastName"
})

In [3]:
df.columns = ["FirstName", "LastName", "Country"]

In [4]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

In [5]:
df = df.rename(columns={
    "Dept": "Department",
    "Sal": "Salary"
})

In [6]:
df = df[["Salary", "Name", "Department"]]

In [7]:
print(df)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

In [8]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [9]:
df.groupby("Store").agg({
    "Sales": "mean",
    "Profit": "mean"
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

In [10]:
df.groupby("Product").agg({
    "Sales": "max",
    "Profit": "min"
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

In [11]:
df.groupby("Store").agg(
    Avg_Sales=("Sales", "mean"),
    Max_Profit=("Profit", "max")
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

In [12]:
df.groupby(["Store", "Product"]).agg({
    "Sales": "sum"
})

               Sales
Store Product
A     Apples     100
      Bananas     90
      Oranges     80
B     Apples     120
      Bananas    110
C     Apples      95
      Bananas    160
      Oranges     60

In [13]:
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

In [14]:
df_joined = df_customers.join(df_orders)
print(df_joined)

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

In [15]:
df_cities = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago"]
}, index=[101, 102, 103])

In [16]:
df_customers = df_customers.join(df_cities)
print(df_customers)

    CustomerName         City
101        Alice     New York
102          Bob  Los Angeles
103      Charlie      Chicago